packages:
  - 'experiments/*'

allowBuilds:
  msw: true
  unrs-resolver: true
  esbuild: true

minimumReleaseAge: 10080 # 7 days
blockExoticSubdeps: true # no git branch as package url

minimumReleaseAgeExclude:
  - 'rolldown'
  - '@oxc-project/types'
  - 'oxlint'
  - '@oxlint/*'
  - 'oxc-transform-react' # rust port of the React Compiler
  - '@oxc-transform-react/*'
  - '@vitejs/plugin-react'
resolutionMode: highest

supportedArchitectures:
  cpu:
    - arm64
    - x64
  os:
    - darwin
    - linux
    - win32
